Alter session set "_oracle_script" = true;
create user SYS_QLNS identified by 1;  
grant create session to SYS_QLNS;
grant create table to SYS_QLNS;
Alter user SYS_QLNS quota 10M on users ;
-- Cấp quyền viết trigger 
GRANT CREATE TRIGGER TO SYS_QLNS; 
GRANT CREATE PROCEDURE TO SYS_QLNS; 
-- 
GRANT UNLIMITED TABLESPACE TO SYS_QLNS; 
GRANT EXECUTE ON DBMS_LOCK TO SYS_QLNS;
-- cẤP NÀY MỚI TẠO ĐƯỢC BẢNG NHATKY có id tự động 
GRANT CREATE SEQUENCE TO SYS_QLNS; 

-- DROP USER SYS_QLNS CASCADE; 

---2.1. Cấp quyền cho user TP_PKT 
CREATE USER TP_PKT  IDENTIFIED BY 1;
grant create session to TP_PKT ; 
Alter user TP_PKT  quota 10M on users ;
-- Cấp quyền thêm, sửa, xóa, xem trên các bảng
GRANT INSERT, UPDATE, DELETE, SELECT ON SYS_QLNS.DONHANG TO TP_PKT ;
GRANT INSERT, UPDATE, DELETE, SELECT ON SYS_QLNS.CHITIETDONHANG TO TP_PKT ;
GRANT INSERT, UPDATE, DELETE, SELECT ON SYS_QLNS.PHIEUNHAP TO TP_PKT ;
GRANT INSERT, UPDATE, DELETE, SELECT ON SYS_QLNS.CHITIETPHIEUNHAP TO TP_PKT ;
GRANT INSERT, UPDATE, DELETE, SELECT ON SYS_QLNS.PHIEUTHU TO TP_PKT ;
GRANT INSERT, UPDATE, DELETE, SELECT ON SYS_QLNS.PHIEUCHI TO TP_PKT ;
GRANT INSERT, UPDATE, DELETE, SELECT ON SYS_QLNS.PHIEUGIAOHANG TO TP_PKT ;
GRANT INSERT, UPDATE, DELETE, SELECT ON SYS_QLNS.KHACHHANG TO TP_PKT ;
GRANT INSERT, UPDATE, DELETE, SELECT ON SYS_QLNS.SACH TO TP_PKT ;
-- Cấp quyền tạo báo cáo
GRANT CREATE PROCEDURE TO TP_PKT;
GRANT CREATE SEQUENCE TO TP_PKT; 
-- 2.2. Cấp quyền cho user NV_PKT (Phòng kế toán):
-- Tạo user NV_PKT và cài đặt mật khẩu
CREATE USER NV_PKT IDENTIFIED BY 1;
grant create session to NV_PKT; 
Alter user NV_PKT quota 10M on users ;
-- Cấp quyền thêm, sửa, xóa, xem trên các bảng
GRANT INSERT, UPDATE,  SELECT ON SYS_QLNS.DONHANG TO NV_PKT;
GRANT INSERT, UPDATE,  SELECT ON SYS_QLNS.CHITIETDONHANG TO NV_PKT;
GRANT INSERT, UPDATE,  SELECT ON SYS_QLNS.PHIEUNHAP TO NV_PKT;
GRANT INSERT, UPDATE,  SELECT ON SYS_QLNS.CHITIETPHIEUNHAP TO NV_PKT;
GRANT INSERT, UPDATE,  SELECT ON SYS_QLNS.PHIEUTHU TO NV_PKT;
GRANT INSERT, UPDATE,  SELECT ON SYS_QLNS.PHIEUCHI TO NV_PKT;
GRANT INSERT, UPDATE,  SELECT ON SYS_QLNS.PHIEUGIAOHANG TO NV_PKT;
GRANT INSERT, UPDATE,  SELECT ON SYS_QLNS.KHACHHANG TO NV_PKT;
GRANT INSERT, UPDATE,  SELECT ON SYS_QLNS.SACH TO NV_PKT;
-- Cấp quyền tạo báo cáo
GRANT CREATE PROCEDURE TO NV_PKT;
GRANT CREATE SEQUENCE TO NV_PKT; 

---3.1. Cấp quyền cho user TP_PKD 
CREATE USER TP_PKD IDENTIFIED BY 1;
grant create session to TP_PKD; 
Alter user TP_PKD quota 10M on users ;
-- Cấp quyền thêm, sửa, xóa, xem trên các bảng
GRANT INSERT, UPDATE, DELETE, SELECT ON SYS_QLNS.DONHANG TO TP_PKD;
GRANT INSERT, UPDATE, DELETE,SELECT ON SYS_QLNS.CHITIETDONHANG TO TP_PKD;
GRANT INSERT, UPDATE, DELETE,SELECT ON SYS_QLNS.PHIEUGIAOHANG TO TP_PKD;
GRANT INSERT, UPDATE, DELETE,SELECT ON SYS_QLNS.SACH TO TP_PKD;
GRANT INSERT, UPDATE, DELETE,SELECT ON SYS_QLNS.KHACHHANG TO TP_PKD;
-- 
GRANT CREATE TRIGGER TO TP_PKD; 
GRANT CREATE PROCEDURE TO TP_PKD;
-- 3.2. Cấp quyền cho user NV_PKD (Phòng kinh doanh):
-- Tạo user NV_PKD và cài đặt mật khẩu
CREATE USER NV_PKD IDENTIFIED BY 1;
grant create session to NV_PKD; 
Alter user NV_PKD quota 10M on users ;
-- Cấp quyền thêm, sửa, xóa, xem trên các bảng
GRANT INSERT, UPDATE, SELECT ON SYS_QLNS.DONHANG TO NV_PKD;
GRANT INSERT, UPDATE, SELECT ON SYS_QLNS.CHITIETDONHANG TO NV_PKD;
GRANT INSERT, UPDATE, SELECT ON SYS_QLNS.PHIEUGIAOHANG TO NV_PKD;
GRANT INSERT, UPDATE, SELECT ON SYS_QLNS.SACH TO NV_PKD;
GRANT INSERT, UPDATE, SELECT ON SYS_QLNS.KHACHHANG TO NV_PKD;
-- 
GRANT CREATE TRIGGER TO NV_PKD; 
GRANT CREATE PROCEDURE TO NV_PKD; 
---4.1. Cấp quyền cho user TP_PQLK 
CREATE USER TP_PQLK IDENTIFIED BY 1;
grant create session to TP_PQLK; 
Alter user TP_PQLK quota 10M on users ; 
-- Cấp quyền thêm, sửa, xóa, xem trên các bảng
GRANT INSERT, UPDATE, DELETE, SELECT ON SYS_QLNS.THELOAI TO TP_PQLK;
GRANT INSERT, UPDATE, DELETE,SELECT ON SYS_QLNS.NHAXUATBAN TO TP_PQLK;
GRANT INSERT, UPDATE, DELETE,SELECT ON SYS_QLNS.KHO TO TP_PQLK;
GRANT INSERT, UPDATE, DELETE,SELECT ON SYS_QLNS.SACH TO TP_PQLK;
GRANT INSERT, UPDATE, DELETE,SELECT ON SYS_QLNS.PHIEUNHAP TO TP_PQLK;
GRANT INSERT, UPDATE, DELETE,SELECT ON SYS_QLNS.CHITIETPHIEUNHAP TO TP_PQLK;
GRANT INSERT, UPDATE, DELETE,SELECT ON SYS_QLNS.NHACUNGCAP TO TP_PQLK;
-- 
GRANT CREATE TRIGGER TO TP_PQLK; 
GRANT CREATE PROCEDURE TO TP_PQLK; 

-- 4.2. Cấp quyền cho user NV_PQLK (Phòng quản lý kho):
-- Tạo user NV_PQLK và cài đặt mật khẩu
CREATE USER NV_PQLK IDENTIFIED BY 1;
grant create session to NV_PQLK; 
Alter user NV_PQLK quota 10M on users ; 
-- Cấp quyền thêm, sửa, xóa, xem trên các bảng
GRANT INSERT, UPDATE, SELECT ON SYS_QLNS.THELOAI TO NV_PQLK;
GRANT INSERT, UPDATE, SELECT ON SYS_QLNS.NHAXUATBAN TO NV_PQLK;
GRANT INSERT, UPDATE, SELECT ON SYS_QLNS.KHO TO NV_PQLK;
GRANT INSERT, UPDATE, SELECT ON SYS_QLNS.SACH TO NV_PQLK;
GRANT INSERT, UPDATE, SELECT ON SYS_QLNS.PHIEUNHAP TO NV_PQLK;
GRANT INSERT, UPDATE, SELECT ON SYS_QLNS.CHITIETPHIEUNHAP TO NV_PQLK;
GRANT INSERT, UPDATE, SELECT ON SYS_QLNS.NHACUNGCAP TO NV_PQLK;
-- 
GRANT CREATE TRIGGER TO NV_PQLK; 
GRANT CREATE PROCEDURE TO NV_PQLK; 












